global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'TaxiService'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:81', 'localhost:82', 'localhost:83', 'localhost:84']
